### ISSUE TITLE
update development containers features by Renovate

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/devcontainers-features-2#4]
https://developer.mend.io/github/suzuki-shunsuke/devcontainers-features-2/-/job/a8798dd9-a897-48f5-87ea-a01935b9d0b3

```
DEBUG: Error extracting dev container JSON file.
{
  "err": {
    "message": "Schema error",
    "stack": "ZodError: Schema error\n    at Object.get error [as error] (/usr/local/renovate/node_modules/.pnpm/zod@3.23.4/node_modules/zod/lib/types.js:55:31)\n    at ZodPipeline.parse (/usr/local/renovate/node_modules/.pnpm/zod@3.23.4/node_modules/zod/lib/types.js:160:22)\n    at Object.extractPackageFile (/usr/local/renovate/lib/modules/manager/devcontainer/extract.ts:17:35)\n    at extractPackageFile (/usr/local/renovate/lib/modules/manager/index.ts:75:9)\n    at getManagerPackageFiles (/usr/local/renovate/lib/workers/repository/extract/manager-files.ts:58:43)\n    at /usr/local/renovate/lib/workers/repository/extract/index.ts:57:28\n    at async Promise.all (index 0)\n    at extractAllDependencies (/usr/local/renovate/lib/workers/repository/extract/index.ts:54:26)\n    at extract (/usr/local/renovate/lib/workers/repository/process/extract-update.ts:140:28)\n    at extractDependencies (/usr/local/renovate/lib/workers/repository/process/index.ts:154:26)\n    at Object.renovateRepository (/usr/local/renovate/lib/workers/repository/index.ts:69:9)\n    at attributes.repository (/usr/local/renovate/lib/workers/global/index.ts:217:11)\n    at start (/usr/local/renovate/lib/workers/global/index.ts:202:7)\n    at /usr/local/renovate/lib/renovate.ts:18:22",
    "issues": "Invalid JSON"
  }
  "packageFile": ".devcontainer/devcontainer.json"
}
```

**Comment by suzuki-shunsuke** [comment]
- https://github.com/renovatebot/renovate/discussions/28794

**Comment by suzuki-shunsuke** [comment]
lock file

https://github.com/devcontainers/spec/blob/main/docs/specs/devcontainer-lockfile.md
